### ISSUE TITLE
Bug with Popout Resizer

### ISSUE THREAD

**Issue by CaosFR** [sPOiDar/fvtt-module-stream-view#23] opened 2022-08-03 10:52 UTC
Hi,

If I use Popout Resizer module with Stream View the X and Y position dont work very well. Can you chect this ?

Without this option in Popout Resizer it's ok :
![Capture](https://user-images.githubusercontent.com/37581932/182592335-a168f74a-d2e3-4134-a533-ebc04ce91421.PNG)

At last, I can disable this option, change position in stream view and enable it.

Thanks

**Comment by sPOiDar** [comment] 2022-08-03 11:14
Yep, I can't fix it sensibly from this side, closing this as duplicate of #16 

And the upstream issue where I suggest how this might be fixed is:

Cardagon/popout-resizer#10

**Closed by sPOiDar** 2022-08-03 11:14 UTC
Labels: duplicate, compatibility

**Comment by CaosFR** [comment] 2022-08-03 12:32
Thanks for your quick reply and sorry for the duplicate (I dont have in closed issues).
