### ISSUE TITLE
OBS web source shows only adventure title image

### ISSUE THREAD

**Issue by struckyCZ** [sPOiDar/fvtt-module-stream-view#6] opened 2021-08-23 11:31 UTC
TL,DR: The interaction menu in the OBS doesn't show the login screen so I cannot login as Streamer.
Hey, I'm not sure if I should try to resolve this here or it's an OBS problem, but I'm having this issue described in the title.
See the image below and please tell me if you have any ideas. I even had to remove the ssl certificates from Foundry config because with them the OBS was showing only blanks screen - via normal browser you can click through "open the page anyway" process but OBS Interact feature doesn't provide any interaction in this matter. 
PS. Followed the installation instructions properly I believe.

![obs](https://user-images.githubusercontent.com/80347865/130440192-25d29132-e93c-470c-b6fb-f927c811e096.png)

**Comment by sPOiDar** [comment] 2021-08-23 12:02
Unfortunately there's not much I can do from my side to help fix deficiencies in the OBS browser source. It is possible to pass chromium/cef flags on the OBS command-line, for example you can start it with `obs --remote-debugging-port=9222` and then open http://localhost:9222 in your browser to gain access to the webview Javscript console and look for errors. You might also be able to do things like force hardware acceleration if it's not working, by using chrome CLI arguments.

As an aside, the SSL certs would either need to be valid for your IP/domain (using LetsEncrypt for example), or you'd need to add the CA to your operating system's trust store if they're self-signed.

An alternative to using the built-in browser source is to just open a new browser session and use window capture.

I'm going to close this issue, because I don't have any real way to troubleshoot problems between OBS and core Foundry, and it works fine for me here (I run Linux though, so there may be differences in how OBS works on other platforms). However if you do manage to work out what's causing this for you, please post your findings here in case someone else runs into the same problem and comes searching.

**Closed by sPOiDar** 2021-08-23 12:02 UTC
Labels: question, wontfix

**Comment by sPOiDar** [comment] 2021-08-30 22:49
Since I had another report of this, I booted a Windows install and fired up the debugger. It looks like the problem is that OBS on Windows bundles an ancient version of CEF, because they haven't managed to get texture copying working on that platform, which would otherwise tank performance. Here's the current state of CEF support for the various platforms:

https://github.com/obsproject/obs-studio/discussions/3853

So, until OBS gets their Windows browser source updated to a recent chromium version, best bet is window capture from another browser session.
