### ISSUE TITLE
Combat Tracker is not displayed/positioned when using Directed camera mode

### ISSUE THREAD

**Issue by Dan5033** [sPOiDar/fvtt-module-stream-view#3] opened 2021-07-13 17:41 UTC
Changing the X and Y value for the position of the Combat Initiative Tracker doesn't change its position. It stays in the middle of the screen.

**Comment by sPOiDar** [comment] 2021-07-13 23:10
I cannot reproduce here, positioning appears to work as expected.

Changing the position settings does not currently dynamically update on the client, you'll need to restart combat or reload to see the position update.

**Comment by Dan5033** [comment] 2021-07-14 06:09
I've perform some experiments to figure out the root of the issue.
The main issue appears when Camera Mode is set to Director in the Module Settings.

It seems that when I disable all my other modules (except the ones required by Stream Viewer), the combat tracker will not appear even when the Auto Show Combat Tracker option is checked.

When I have my module suite enabled, the combat tracker is shown (maybe by some other module) but the position is not set to the ones in Module Settings. Instead, it's just smack dab in the center

All works as normal when Directed mode is set to Automatic

**Comment by sPOiDar** [comment] 2021-07-14 06:52
Thanks for looking into this, I can reproduce the lack of combat tracker with `Directed` camera mode, I'll look into it and try to get a fix out soon.

**Comment by sPOiDar** [comment] 2021-07-14 07:01
Fixed in v0.1.5

**Closed** 2021-07-14 07:00 UTC
Labels: bug
