### ISSUE TITLE
[BUG] Audio not working on streamed actor

### ISSUE THREAD

**Issue by davelamorte** [sPOiDar/fvtt-module-stream-view#48] opened 2022-11-30 09:19 UTC
Description:
The streamed actor's view, is missing all the sounds coming from Foundry, since update to version 10.290 (it was working fine with the previous V10 build).
The only way to have the sounds work again, is to activate the option "Show Full Sidebar [WARNING]"; when this is disabled (as it should be), no sounds work, playlist, ambient and interface, nothing at all.

Stream View 1.3.0
Foundry 10.290
DND 5E 2.0.3
Server Foundry Client/server on Windows 10
Client for streaming: OBS

**Comment by sPOiDar** [comment] 2022-11-30 09:44
Can't reproduce here. Browsers do have a restriction that the page must be interacted with before it's allowed to play audio - just clicking the page once is enough, can you try that? When using the OBS browser source I don't even need to do that, I am on Linux though so the browser source might behave differently on Windows.

Not sure how having the sidebar displayed would work around that though, shouldn't be able to circumvent that requirement.

**Comment by davelamorte** [comment] 2022-12-03 17:13
I have just updated Foundry to 291.
Indeed like you said, now it starts with no sound, but if after the canvas is completely loaded, I use "interact" and I click on it, the sound starts streaming correctly.

I can't check if the same behavior was happening on 290 now, but I'm quite sure I've interacted with the canvas multiple times, and the sound never started.
So, hopefully now it's kinda fixed on its own?
I wish there was a way to avoid the need to interact though, it's dangerous, if I refresh for any reason the page, I might not notice that the sound is cut off.

**Comment by sPOiDar** [comment] 2022-12-03 21:17
Browsers have required this interaction for quite some time now, they do it to prevent horrible auto-play ads that became common a while ago. They're meant to like, learn sites you visit, but it's some opaque algorithm, and I don't think there's a toggle anywhere to explicitly allow a certain site.

You can try starting Chrome/OBS with the `--autoplay-policy=no-user-gesture-required` flag just for the Foundry session, which may or may not still exist or work.

In any case, this is not a Stream View issue, not even really a Foundry issue, so going to close this out here.

**Closed by sPOiDar** 2022-12-03 21:17 UTC
Labels: invalid
