### ISSUE TITLE
Chat stop refresh

### ISSUE THREAD

**Issue by CaosFR** [sPOiDar/fvtt-module-stream-view#29] opened 2022-09-08 15:43 UTC
Hi,

Thanks for your module. When I use the stream view, sometimes the chat stop be refresh and no new entry is add. I have to delete the chat archive. It's competely random and I dont have any error in the console.

NB : I use DFreed and Illandril's Chat Enchancement

Tell me if you need some more usefull informations.
Thanks

**Comment by sPOiDar** [comment] 2022-09-08 22:07
I suspect your problem is with a different module - all Stream View does is pop out chat (same as if you right-click the chat icon in the toolbar), so I'd check if you can: a) reproduce with no other modules than Stream View; and/or b) reproduce without Stream View by just popping out the chat.

**Comment by CaosFR** [comment] 2022-09-21 15:35
Hi, sorry for the delays. I try to find to "why" I have this problem.
a) It's difficult to repoduce, it's completely random.
b) I have try before post and I dont have any problem.

**Comment by sPOiDar** [comment] 2022-09-21 21:40
I'm quite confident the issue is not with Stream View. I think I saw that there was some kind of chat bug in core Foundry that was fixed in recent versions too. Either way, I'll close this out here for now, if you do manage to attribute this to Stream View feel free to reopen.

**Closed by sPOiDar** 2022-09-21 21:40 UTC
Labels: question

**Comment by CaosFR** [comment] 2022-09-22 15:16
I understand, happy dev.
