### ISSUE TITLE
[bug] [levels] doesn't handle multi levels scenes

### ISSUE THREAD

**Issue by lefoudre** [sPOiDar/fvtt-module-stream-view#69] opened 2023-08-24 11:43 UTC
Using foundry 11.
While streaming a scene with levels, the "stream view" only shows the top ans not each levels

**Comment by sPOiDar** [comment] 2023-08-24 16:35
Duplicate of #21

Unfortunately Levels is designed to only work with a single selected token.

**Closed by sPOiDar** 2023-08-24 16:35 UTC
Labels: duplicate
