### ISSUE TITLE
[feat] Levels breaks line of sight with multiple tokens

### ISSUE THREAD

**Issue by Conradhowlf** [sPOiDar/fvtt-module-stream-view#74] opened 2023-12-29 22:24 UTC
**Is your feature request related to a problem? Please describe.**
So, I use streamview to record my sessions, but I also use levels to handle maps.
I problem I'm getting comes from the interaction between a selected token, and the map itself, let me show it in a video:
https://www.youtube.com/watch?v=axoXNZF7RTw&ab_channel=EpicQuesters
As you can see in a video, if I deselect a token, I can see the vision of the other "observed" "owned" tokens, but since he is in a level above, all the walls break and they can see things they shouldn't, in this case, the treasure room to the south.

**Describe the solution you'd like**
Is there a way to, when I deselect tokens or when I choose a token that the Streamview client does not have access to, for it to preserve the last selected token? Because if it does not, it takes a view of all tokens he has access to, and it breaks the scene while using levels.

**Describe alternatives you've considered**
Any solutions would be welcome really, haha
If there is an alternative to handling this via macro or something like that

**Additional context**
How the vision is normally:
![image](https://github.com/sPOiDar/fvtt-module-stream-view/assets/81392963/e7f5edb0-8aba-4086-a5b0-549c92153e6a)
The vision from the player above:
![image](https://github.com/sPOiDar/fvtt-module-stream-view/assets/81392963/260539ef-c2a9-4402-9932-5aa5c866b7b1)
What happens when there are no selected tokens:
![image](https://github.com/sPOiDar/fvtt-module-stream-view/assets/81392963/a284e840-177e-42f9-a626-f6ce03eeed8a)
How the map actually is without walls:
![image](https://github.com/sPOiDar/fvtt-module-stream-view/assets/81392963/4226c824-9060-4c04-a4ac-8af4218c7e20)

**Comment by sPOiDar** [comment] 2023-12-30 00:20
StreamView isn't doing anything special here - looks like Levels is breaking LoS for some reason when there are multiple tokens with vision, same thing would likely happen if you had a player with multiple token ownership, like a ranger pet or summon. This probably needs to be fixed inside Levels.

**Closed as completed by sPOiDar** 2023-12-30 00:20 UTC
Labels: enhancement, invalid, compatibility

**Comment by Conradhowlf** [comment] 2023-12-30 00:55
> StreamView isn't doing anything special here - looks like Levels is breaking LoS for some reason when there are multiple tokens with vision, same thing would likely happen if you had a player with multiple token ownership, like a ranger pet or summon. This probably needs to be fixed inside Levels.

Yes, I do realize that, but is there a way to circunvent that by making StreamView always have at least one token selected. Is this possible? Lets say Im controlling token Player1, and then I as a DM select CreatureToken1, the StreamView client will deselect the Player1, and give vision to all owned tokens right? Is there a way to not do that, to keep the last selected player token on the StreamView client so you wont lose the last vision you had?

**Comment by sPOiDar** [comment] 2023-12-30 03:26
Not impossible, but it would be a hack, and would go against the more common expectation of how things should work - I'd prefer not to add such a hack here when the problem is clearly caused by the core behaviour of a different module.
