### ISSUE TITLE
Can't change combat tracker position

### ISSUE THREAD

**Issue by DragonZaid** [sPOiDar/fvtt-module-stream-view#17] opened 2022-03-11 19:27 UTC
I'm not sure why, but I can't seem to change the position of the combat tracker in the stream view using the module settings. I was, however, able to move the chat log. The combat tracker is always located at the top of the window, near the left side, regardless of the pixel settings.

**Comment by sPOiDar** [comment] 2022-03-11 23:06
Working as expected here. I would guess there's some sort of module conflict, please try to reproduce in a world with just Stream View enabled.

If it works with just this module enabled, try enabling other modules until you find the one that's causing the problem and we'll see if we can get them to be compatible.

**Comment by CasualTerror** [comment] 2022-05-12 22:38
I also can't change the combat tracker position. I can't even turn the auto combat tracker off.

**Comment by sPOiDar** [comment] 2022-05-12 22:48
Do you have problems in a world with just Stream View enabled? Both of these features test as working fine here, and I can't really investigate without knowing whether it's a particular module that is causing the issue.

**Comment by CasualTerror** [comment] 2022-05-12 23:00
I found the culprit. It is [popout resizer](https://github.com/Cardagon/popout-resizer). 

I don't know why for a while I couldn't turn the combat tracker off. That issue has fixed itself.

**Comment by sPOiDar** [comment] 2022-05-12 23:07
Gotcha, going to close this as a duplicate of #16 

And the corresponding Popout Resizer issue:

https://github.com/Cardagon/popout-resizer/issues/10

**Closed by sPOiDar** 2022-05-12 23:07 UTC
Labels: duplicate
