### ISSUE TITLE
Currently, view does not factor in token's elevation, which causes problems with levels.

### ISSUE THREAD

**Issue by ElectrumDC30** [sPOiDar/fvtt-module-stream-view#59] opened 2023-05-13 07:53 UTC
You can see examples of this on my latest stream vod here: https://youtu.be/ucSjsVPAJes?t=5565

Basically, as it currently stands, if I want the stream view to factor in the token's elevational perspective, I.E if they're actually above a roof or an overhead layer, I have to manually use the "Interact" fcuntion in OBS and click on said token, not the biggest issue in the world but is there any way the stream view could be modified to, i dunno, click once on the currently tracked token so that the perspective shifts?

**Comment by sPOiDar** [comment] 2023-05-13 08:26
Levels unfortunately is not expected to work with Stream View as Levels does not work with Foundry observers, and I'm not sure that Levels can cope in any way sensibly when trying to view multiple tokens at the same time. I don't think there's anything sane I can do on this side to make Levels work better for this scenario without hacking deep into its internals, sorry.

Duplicate of #21

**Closed by sPOiDar** 2023-05-13 08:26 UTC
Labels: duplicate, wontfix, compatibility

**Comment by ElectrumDC30** [comment] 2023-05-13 08:30
I'll admit I don't know very much about coding, I just thought I'd ask since manually clicking on the curretnly tracked token did work, is there no way to get the viewer to, like, click on the currently tracked token when the combat tracker is set to them? that would honestly be enough on it's own, I can imagine in manual stream view, it'd be impossible but I'm wondering if in just combat tracked view there's any way to "set to current token view" or something

**Comment by pdf** [comment] 2023-05-13 08:51
During combat, #58 may solve the problem for you, provided the stream user has the Owner permission on all your tokens - I need to find some time to review and merge that change, but my home Internet is down so not sure if I'll get a chance this week.

Out of combat though, I'm afraid Levels still won't work well even after that change.

**Comment by sPOiDar** [comment] 2023-05-13 08:52
During combat, #58 may solve the problem for you, provided the stream user has the Owner permission on all your tokens - I need to find some time to review and merge that change, but my home Internet is down so not sure if I'll get a chance this week.

Out of combat though, I'm afraid Levels still won't work well even after that change.

**Comment by ElectrumDC30** [comment] 2023-05-13 11:33
oh out of combat that's totally fine, I can manouver manually well enough out of combat. was just IN combat, when i need to focus on other things that it's most helpful, i'll have a look at 58, thanks so much!
